name: Pages
author: Ht-ui
url: https://ht-ui.github.io/pages.github.io/
baseurl: 
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 6ab1fb6e863dab49bf8a
    clientSecret : e6f3da5e9ffd0627b34faf2a77b763fa6fa73065
    repo : pages
    owner : Ht-ui
    admin : [Ht-ui]
