name: Pages
author: Ht-ui
url: https://ht-ui.github.io/pages.github.io
baseurl: 
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 714815292d25c37bb8e3
    clientSecret : 66c01b86aad9999d5042bb7932b2d209486fe7ac
    repo : pages
    owner : Ht-ui
    admin : [Ht-ui]
